
project_id = "gqnzsnzolqvsalyzbhmq"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[realtime]
enabled = true

[functions.meta-conversion-track]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.enrollment-notification]
verify_jwt = false

[functions.send-contact-notification]
verify_jwt = false

[functions.generate-narrative]
verify_jwt = false
