
import { useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { toast } from '@/components/ui/use-toast';
import { getOAuthRedirectUrl } from './auth-utils';

export const useSignIn = (setError?: (error: string | null) => void) => {
  const [isLoading, setIsLoading] = useState(false);
  
  const signIn = async (email: string, password: string) => {
    setIsLoading(true);
    try {
      const { error } = await supabase.auth.signInWithPassword({ email, password });
      
      if (error) {
        throw error;
      }
    } catch (error: any) {
      if (setError) {
        setError(error.message);
      }
      toast({
        title: "Sign in failed",
        description: error.message,
        variant: "destructive",
      });
      throw error;
    } finally {
      setIsLoading(false);
    }
  };
  
  return {
    signIn,
    isLoading
  };
};

export const useSignInWithGoogle = (setError?: (error: string | null) => void) => {
  const [isLoading, setIsLoading] = useState(false);
  
  const signInWithGoogle = async () => {
    setIsLoading(true);
    try {
      const redirectTo = getOAuthRedirectUrl();
      
      // Log debugging information about the auth attempt
      console.log("=== GOOGLE AUTH INITIALIZATION ===");
      console.log("Initiating Google sign-in");
      console.log("Current URL:", window.location.href);
      console.log("Current hostname:", window.location.hostname);
      console.log("Current origin:", window.location.origin);
      console.log("Redirect URL to be used:", redirectTo);
      console.log("Browser localStorage available:", typeof localStorage !== 'undefined');
      console.log("Browser cookies enabled:", navigator.cookieEnabled);
      
      // Clear any existing cookies to avoid conflicts
      document.cookie.split(';').forEach(cookie => {
        const trimmedCookie = cookie.trim();
        const cookieName = trimmedCookie.split('=')[0];
        
        // Only clear non-essential cookies
        if (cookieName && 
            !cookieName.includes('_csrf') && 
            !cookieName.includes('__Host')) {
          console.log("Clearing cookie:", cookieName);
          document.cookie = `${cookieName}=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;`;
        }
      });
      
      // Clear related localStorage items to ensure a fresh auth session
      localStorage.removeItem('supabase.auth.token');
      localStorage.removeItem('supabase.auth.refreshToken');
      
      const { data, error } = await supabase.auth.signInWithOAuth({
        provider: 'google',
        options: {
          redirectTo: redirectTo,
          queryParams: {
            access_type: 'offline',
            prompt: 'consent',
          },
          // Explicitly use PKCE flow
          flowType: 'pkce'
        }
      });
      
      if (error) {
        console.error("=== GOOGLE AUTH ERROR ===");
        console.error("OAuth initialization error:", error);
        throw error;
      }
      
      if (data?.url) {
        console.log("=== GOOGLE AUTH REDIRECT ===");
        console.log("OAuth redirect URL generated:", data.url);
        // Force the browser to use this URL
        window.location.href = data.url;
      } else {
        console.error("=== GOOGLE AUTH ERROR ===");
        console.error("No redirect URL was generated by Supabase");
        throw new Error("Authentication provider did not return a redirect URL");
      }
    } catch (error: any) {
      console.error("=== GOOGLE AUTH EXCEPTION ===");
      console.error("Sign-in exception:", error);
      if (setError) {
        setError(error.message || "Failed to connect to Google authentication service");
      }
      toast({
        title: "Google sign in failed",
        description: error.message || "Failed to connect to Google authentication service",
        variant: "destructive",
      });
      // Don't throw error here to allow for UI recovery
      setIsLoading(false);
    } finally {
      setIsLoading(false);
    }
  };
  
  return {
    signInWithGoogle,
    isLoading
  };
};
