
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqnzsnzolqvsalyzbhmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxbnpzbnpvbHF2c2FseXpiaG1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NDM1NDAsImV4cCI6MjA2MTIxOTU0MH0.p2zZF0qAeMtXerm8f68E38ZGj2OYZ9t4Sqyu_oqyjMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Custom storage implementation that logs operations for debugging
const customStorage = typeof window !== 'undefined' ? {
  getItem: (key: string) => {
    const item = localStorage.getItem(key);
    console.log(`[PKCE Debug] Getting ${key} from storage`, item ? "found" : "not found");
    return item;
  },
  setItem: (key: string, value: string) => {
    console.log(`[PKCE Debug] Setting ${key} in storage`);
    localStorage.setItem(key, value);
  },
  removeItem: (key: string) => {
    console.log(`[PKCE Debug] Removing ${key} from storage`);
    localStorage.removeItem(key);
  },
} : undefined;

// Create the Supabase client with explicit storage configuration to ensure
// PKCE flow works correctly with proper storage of code verifiers
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      flowType: 'pkce',
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
      storage: customStorage
    }
  }
);

// Initialize auth environment on client load
if (typeof window !== 'undefined') {
  // Debug logging for auth configuration
  console.log("[Supabase Auth] Initializing in environment:", 
    import.meta.env.MODE || "unknown",
    "URL:", window.location.href);
  
  // Check for auth parameters in URL early
  if (window.location.href.includes('code=') && window.location.href.includes('state=')) {
    console.log("[Supabase Auth] Auth parameters detected in URL - PKCE flow started");
    
    // Force reload code verifier from storage to ensure it's available
    const codeVerifier = localStorage.getItem('supabase.auth.code_verifier');
    console.log("[Supabase Auth] Code verifier available:", !!codeVerifier);
    
    if (!codeVerifier) {
      console.warn("[Supabase Auth] No code verifier found in storage. Auth may fail.");
    }
  }

  // Clear any lingering service worker cache that might interfere with auth
  if ('caches' in window) {
    caches.keys().then(names => {
      names.forEach(name => {
        if (name.includes('supabase') || name.includes('auth')) {
          console.log("[Supabase Auth] Clearing cache:", name);
          caches.delete(name);
        }
      });
    });
  }
}

// Log initialization 
console.log("[Supabase Auth] Client initialized with PKCE flow enabled");
